--------------------------------------------------------
-- Archivo creado  - lunes-agosto-10-2026   
--------------------------------------------------------

DEFINE BASE_PATH_NO_VERSIONABLES = "C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables"
DEFINE BASE_PATH_VERSIONABLES = "C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\Versionables"

@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_VERSION.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ATRIBUTO.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_COMPONENTE.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DATO_ELEMENTO.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DIRECCION.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_PADRE.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ESTRUCTURA.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PARAMETRO.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA_DATO_PERSONAL.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA_DIRECCION.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_ITEM.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_ROL.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_SISTEMA.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_SUBCOMPONENTE.sql"
@"&BASE_PATH_NO_VERSIONALES.\SYS_C0022298.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_IDX1.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_IDX2.sql"
@"&BASE_PATH_NO_VERSIONALES.\SYS_C0022703.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_VERSION_IDX1.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_VERSION_IDX2.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_VERSION_JSON_IDX.sql"
@"&BASE_PATH_NO_VERSIONALES.\GLR_ATRIBUTOS_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_COMPONENTE_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DATO_ELEMENTO_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\SYS_C0021566.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_PADRE_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\SYS_C0022779.sql"
@"&BASE_PATH_NO_VERSIONALES.\PARAMETRO_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\IDX_PARAMETRO_VIGENTE.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONAS_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GDP_DATOSPERSONA_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_ITEM_PK.sql"
@"&BASE_PATH_NO_VERSIONALES.\IDX_REFITEM_VALIDACION.sql"
@"&BASE_PATH_NO_VERSIONALES.\IDX_REFERENCIA_ITEM_VIGENTE.sql"
@"&BASE_PATH_NO_VERSIONALES.\PK_REFERENCIA_ROL.sql"
@"&BASE_PATH_NO_VERSIONALES.\PK_REFERENCIA_SISTEMA.sql"
@"&BASE_PATH_NO_VERSIONALES.\TRGG_ARCHIVO.sql"
@"&BASE_PATH_NO_VERSIONALES.\TRGG_ARCHIVO_VERSION.sql"
@"&BASE_PATH_NO_VERSIONALES.\INSERT_ID_DIRECCION.sql"
@"&BASE_PATH_NO_VERSIONALES.\TRG_VALIDA_GRL_PARAMETRO.sql"
@"&BASE_PATH_NO_VERSIONALES.\TRG_VALIDA_GRL_PARAMETRO_FK.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ARCHIVO_VERSION_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ATRIBUTO_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_COMPONENTE_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DATO_ELEMENTO_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DIRECCION_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_PADRE_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ESTRUCTURA_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PARAMETRO_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA_DATO_PERSONAL_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_PERSONA_DIRECCION_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_ITEM_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_ROL_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_REFERENCIA_SISTEMA_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_SUBCOMPONENTE_CONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ATRIBUTO_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_COMPONENTE_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_DATO_ELEMENTO_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ELEMENTO_PADRE_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_ESTRUCTURA_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\GRL_SUBCOMPONENTE_REFCONSTRAINT.sql"
@"&BASE_PATH_NO_VERSIONALES.\SEQUENCES.sql"
@"&BASE_PATH_NO_VERSIONALES.\TYPES.sql"

@"&BASE_PATH_VERSIONABLES.\PKG_REFERENCIA_ITEM.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_DATO_ELEMENTO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_SUBCOMPONENTE.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_CONFIG.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_VALIDACIONES.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_REFERENCIA.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ATRIBUTO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_REFERENCIA_ROL.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_PARAMETRO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_REFERENCIA_SISTEMA.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_VISORES.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_LOG.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ARCHIVO_VERSION.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_VALIDATOR.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ARCHIVO_COMBINADO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_COMPONENTE.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ELEMENTO_PADRE.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ESTRUCTURA.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_ESTRUCTURA_NEGOCIO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_UTILIDADES.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_PERSONA.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ELEMENTO.sql"
@"&BASE_PATH_VERSIONABLES.\PKG_GRL_ARCHIVO.sql"


BEGIN
  FOR i IN 1..5 LOOP
    FOR rec IN (
      SELECT object_name, object_type
      FROM user_objects
      WHERE object_type IN ('PACKAGE','PACKAGE BODY')
        AND status = 'INVALID'
    ) LOOP
      BEGIN
        IF rec.object_type = 'PACKAGE' THEN
          EXECUTE IMMEDIATE 'ALTER PACKAGE ' || rec.object_name || ' COMPILE';
        ELSE
          EXECUTE IMMEDIATE 'ALTER PACKAGE ' || rec.object_name || ' COMPILE BODY';
        END IF;
      EXCEPTION WHEN OTHERS THEN
        NULL; -- lo intenta de nuevo en la siguiente pasada
      END;
    END LOOP;
  END LOOP;
END;
/

-- Para revisar si quedó algo pendiente:
/*SELECT object_name, object_type, status
FROM user_objects
WHERE object_type IN ('PACKAGE','PACKAGE BODY')
  AND status = 'INVALID';
*/