--------------------------------------------------------
-- Archivo creado  - lunes-agosto-10-2026   
--------------------------------------------------------
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_VERSION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ATRIBUTO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_COMPONENTE.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DATO_ELEMENTO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DIRECCION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_PADRE.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ESTRUCTURA.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PARAMETRO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA_DATO_PERSONAL.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA_DIRECCION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_ITEM.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_ROL.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_SISTEMA.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_SUBCOMPONENTE.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\SYS_C0022298.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_IDX1.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_IDX2.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\SYS_C0022703.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_VERSION_IDX1.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_VERSION_IDX2.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_VERSION_JSON_IDX.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GLR_ATRIBUTOS_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_COMPONENTE_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DATO_ELEMENTO_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\SYS_C0021566.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_PADRE_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\SYS_C0022779.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\PARAMETRO_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\IDX_PARAMETRO_VIGENTE.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONAS_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GDP_DATOSPERSONA_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_ITEM_PK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\IDX_REFITEM_VALIDACION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\IDX_REFERENCIA_ITEM_VIGENTE.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\PK_REFERENCIA_ROL.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\PK_REFERENCIA_SISTEMA.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\TRGG_ARCHIVO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\TRGG_ARCHIVO_VERSION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\INSERT_ID_DIRECCION.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\TRG_VALIDA_GRL_PARAMETRO.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\TRG_VALIDA_GRL_PARAMETRO_FK.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ARCHIVO_VERSION_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ATRIBUTO_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_COMPONENTE_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DATO_ELEMENTO_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DIRECCION_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_PADRE_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ESTRUCTURA_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PARAMETRO_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA_DATO_PERSONAL_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_PERSONA_DIRECCION_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_ITEM_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_ROL_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_REFERENCIA_SISTEMA_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_SUBCOMPONENTE_CONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ATRIBUTO_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_COMPONENTE_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_DATO_ELEMENTO_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ELEMENTO_PADRE_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_ESTRUCTURA_REFCONSTRAINT.sql
@C:\Users\Camilo Donoso\Documents\TESTING\BBDD QA\GENERALIDADES\No versionables\GRL_SUBCOMPONENTE_REFCONSTRAINT.sql
