--------------------------------------------------------
--  DDL for Table GRL_PERSONA
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_PERSONA" 
   (	"ID_PERSONA" NUMBER, 
	"IDENTIFICADOR" VARCHAR2(20 CHAR), 
	"ID_TIPO_ID" NUMBER, 
	"NOMBRES" VARCHAR2(40 CHAR), 
	"PRIMER_APELLIDO" VARCHAR2(25 CHAR), 
	"SEGUNDO_APELLIDO" VARCHAR2(25 CHAR), 
	"FECHA_NAC" DATE, 
	"NOMBRE_SOCIAL" VARCHAR2(30 CHAR), 
	"ID_SEXO" NUMBER, 
	"ID_GENERO" NUMBER, 
	"OTRO_GENERO" VARCHAR2(20 CHAR), 
	"CON_DISCAPACIDAD" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"DISCAPACIDAD" VARCHAR2(30 CHAR), 
	"ID_NACIONALIDAD" NUMBER, 
	"FALLECIDO" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"ID_USUARIO_MOD" NUMBER, 
	"FEC_ULT_MOD" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."ID_PERSONA" IS 'ID único de la persona, PK.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."IDENTIFICADOR" IS 'ID nacional de la persona, RUT, DNI, Pasaporte, etc.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."ID_TIPO_ID" IS 'ID del tipo de identificador, RUT Chile, DNI Perú, Pasaporte, etc..'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."NOMBRES" IS 'Nombre registral de la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."PRIMER_APELLIDO" IS 'Primer apellido registral de la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."SEGUNDO_APELLIDO" IS 'Segundo apellido registral de la persona, opcional.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."FECHA_NAC" IS 'Fecha de nacimiento de la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."NOMBRE_SOCIAL" IS 'Nombre social autorizado por DGP (Direccion de Genereo), opcional.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."ID_SEXO" IS 'ID sexo registral de la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."ID_GENERO" IS 'ID genero percibido por la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."OTRO_GENERO" IS 'Otro género.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."CON_DISCAPACIDAD" IS 'Indica si la persona tiene alguna discapacidad válida (S/N).'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."DISCAPACIDAD" IS 'Nombre de la discapacidad.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."ID_NACIONALIDAD" IS 'ID del pais de nacionalidad.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA"."FALLECIDO" IS 'Indica si la persona esta fallecida (S/N).'
   COMMENT ON TABLE "GENERALIDADES"."GRL_PERSONA"  IS 'Tabla que registra los datos básicoa de las personas independiente del tipo.'
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA" TO "SECRETARIAGRALDTIC"
  GRANT REFERENCES ON "GENERALIDADES"."GRL_PERSONA" TO "SECRETARIAGRALDTIC"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA" TO "SIGESUSTIC"
  GRANT REFERENCES ON "GENERALIDADES"."GRL_PERSONA" TO "SIGESUSTIC"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA" TO "SIEVAUTIC"
  GRANT REFERENCES ON "GENERALIDADES"."GRL_PERSONA" TO "SIEVAUTIC"
  GRANT REFERENCES ON "GENERALIDADES"."GRL_PERSONA" TO "DACIDTIC"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA" TO "DACIDTIC"
