--------------------------------------------------------
--  DDL for Table GRL_COMPONENTE
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_COMPONENTE" 
   (	"ID_ESTRUCTURA" NUMBER, 
	"ID_COMPONENTE" NUMBER, 
	"NOMBRE" VARCHAR2(60 CHAR), 
	"DESCRIPCION" VARCHAR2(2000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_COMPONENTE"."ID_COMPONENTE" IS 'ID del COMPONENTE.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_COMPONENTE"."DESCRIPCION" IS 'Describe para que es el COMPONENTE.'
