--------------------------------------------------------
--  Constraints for Table GRL_ELEMENTO_PADRE
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" MODIFY ("ID_ITEM" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" MODIFY ("ID_PADRE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" ADD CONSTRAINT "GRL_ELEMENTO_PADRE_PK" PRIMARY KEY ("ID_ITEM", "ID_PADRE")
  USING INDEX "GENERALIDADES"."GRL_ELEMENTO_PADRE_PK"  ENABLE
