--------------------------------------------------------
--  Constraints for Table GRL_ATRIBUTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" MODIFY ("ID_ATRIBUTO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" MODIFY ("ID_COMPONENTE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" MODIFY ("ID_TIPO_DATO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" MODIFY ("ID_ESTADO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" ADD CONSTRAINT "GLR_ATRIBUTOS_PK" PRIMARY KEY ("ID_ATRIBUTO")
  USING INDEX "GENERALIDADES"."GLR_ATRIBUTOS_PK"  ENABLE
