--------------------------------------------------------
--  DDL for Table GRL_ELEMENTO
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ELEMENTO" 
   (	"ID_ITEM" NUMBER, 
	"NOMBRE" VARCHAR2(60 CHAR), 
	"ID_COMPONENTE" NUMBER, 
	"ID_PADRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO"."ID_ITEM" IS 'ID del elemento en la estructura.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO"."NOMBRE" IS 'Nombre del elemento ingresado a una estructura'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO"."ID_COMPONENTE" IS 'ID del COMPONENTE en la estructura'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO"."ID_PADRE" IS 'ID del elemento padre en la estructura'
