--------------------------------------------------------
--  Ref Constraints for Table GRL_DATO_ELEMENTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" ADD CONSTRAINT "GRL_DATO_ELEMENTO_ATRIBUTO_FK" FOREIGN KEY ("ID_ATRIBUTO")
	  REFERENCES "GENERALIDADES"."GRL_ATRIBUTO" ("ID_ATRIBUTO") ENABLE NOVALIDATE
  ALTER TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" ADD CONSTRAINT "GRL_DATO_ELEMENTO_ELEMENTO_FK" FOREIGN KEY ("ID_ITEM")
	  REFERENCES "GENERALIDADES"."GRL_ELEMENTO" ("ID_ITEM") ENABLE NOVALIDATE
