--------------------------------------------------------
--  DDL for Table GRL_ARCHIVO_VERSION
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" 
   (	"ID_VERSION" NUMBER, 
	"ID_ARCHIVO" NUMBER, 
	"FECHA_MODIFICACION" DATE DEFAULT SYSDATE, 
	"ESTADO" VARCHAR2(20 CHAR) DEFAULT 0, 
	"METADATA" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 
 LOB ("METADATA") STORE AS SECUREFILE (
  TABLESPACE "GENERALIDADES_DATA" ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO_VERSION"."ID_VERSION" IS 'id unico para la version de archivo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO_VERSION"."ID_ARCHIVO" IS 'id de que archivo pertenece laactualizacion'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO_VERSION"."FECHA_MODIFICACION" IS 'fecha que se subio la actualizacion'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO_VERSION"."ESTADO" IS 'estado de activo o desactivado del archivo actualizado'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO_VERSION"."METADATA" IS 'Metadatos en formato JSON asociados a la versión'
   COMMENT ON TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION"  IS 'Historial de versiones de archivo'
  GRANT SELECT ON "GENERALIDADES"."GRL_ARCHIVO_VERSION" TO "SECRETARIAGRALDTIC"
