--------------------------------------------------------
--  Constraints for Table GRL_ELEMENTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" MODIFY ("ID_ITEM" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" MODIFY ("ID_COMPONENTE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" ADD CONSTRAINT "GRL_ELEMENTO_PK" PRIMARY KEY ("ID_ITEM")
  USING INDEX "GENERALIDADES"."GRL_ELEMENTO_PK"  ENABLE
