--------------------------------------------------------
--  DDL for Table GRL_ARCHIVO
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ARCHIVO" 
   (	"ID_ARCHIVO" NUMBER, 
	"NOMBRE" VARCHAR2(255 CHAR), 
	"ALIAS" VARCHAR2(255 CHAR), 
	"RUTA" VARCHAR2(2000 CHAR), 
	"ESTADO" VARCHAR2(20 CHAR) DEFAULT 1, 
	"APP" VARCHAR2(255 CHAR), 
	"USUARIO" VARCHAR2(255 CHAR), 
	"FECHA_SUBIDA" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."ID_ARCHIVO" IS 'id unico que tendra el archivo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."NOMBRE" IS 'nombre que tendra el archivo para mostrarse al usuario'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."ALIAS" IS 'nombre ficticio que se le da al archivo para subirlo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."RUTA" IS 'Ruta o URI donde vive el binario'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."ESTADO" IS 'estado que se encuentra el archivo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."APP" IS 'nombre de que aplicacion se esta subiendo el archivo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."USUARIO" IS 'id de usuario que ingreso el archivo'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ARCHIVO"."FECHA_SUBIDA" IS 'fecha que se subio el archivo'
   COMMENT ON TABLE "GENERALIDADES"."GRL_ARCHIVO"  IS 'Entidad lógica del archivo'
  GRANT SELECT ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT ALTER ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT DELETE ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT INDEX ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT INSERT ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT UPDATE ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT REFERENCES ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT READ ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT ON COMMIT REFRESH ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT QUERY REWRITE ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT DEBUG ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
  GRANT FLASHBACK ON "GENERALIDADES"."GRL_ARCHIVO" TO "SECRETARIAGRALDTIC"
