--------------------------------------------------------
--  Constraints for Table GRL_REFERENCIA_ITEM
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" MODIFY ("ID_ITEM" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" MODIFY ("ID_REFERENCIA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" MODIFY ("NIVEL" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" MODIFY ("ID_ESTADO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" ADD CONSTRAINT "GRL_REFERENCIA_ITEM_PK" PRIMARY KEY ("ID_ITEM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE
