--------------------------------------------------------
--  DDL for Table GRL_PERSONA_DIRECCION
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_PERSONA_DIRECCION" 
   (	"ID_PERSONA" NUMBER, 
	"ID_DIRECCION" NUMBER, 
	"ID_TIPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DIRECCION"."ID_PERSONA" IS 'ID de la persona.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DIRECCION"."ID_DIRECCION" IS 'ID de la dirección.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DIRECCION"."ID_TIPO" IS 'ID del tipo de dirección.'
   COMMENT ON TABLE "GENERALIDADES"."GRL_PERSONA_DIRECCION"  IS 'Tabla que relaciona la persona con sus direcciones regsitradas.'
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "AUDITOR"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPLOG"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGESUSTIC"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSSGU"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIREPER"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSRP"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGETIC"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSTK"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "AUDITOR"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPLOG"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGESUSTIC"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSSGU"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIREPER"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSRP"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGETIC"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSTK"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "AUDITOR"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPLOG"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGESUSTIC"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSSGU"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIREPER"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSRP"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGETIC"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSTK"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "AUDITOR"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPLOG"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGESUSTIC"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSSGU"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIREPER"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSRP"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "SIGETIC"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPSTK"
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPGRL"
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPGRL"
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPGRL"
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DIRECCION" TO "APPGRL"
