--------------------------------------------------------
--  DDL for Table GRL_SUBCOMPONENTE
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_SUBCOMPONENTE" 
   (	"ID_COMPONENTE" NUMBER, 
	"ID_PADRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA" 

   COMMENT ON COLUMN "GENERALIDADES"."GRL_SUBCOMPONENTE"."ID_COMPONENTE" IS 'ID del COMPONENTE.'
   COMMENT ON COLUMN "GENERALIDADES"."GRL_SUBCOMPONENTE"."ID_PADRE" IS 'ID del COMPONENTE padre del que depende el COMPONENTE.'
