--------------------------------------------------------
--  Constraints for Table GRL_ARCHIVO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO" ADD PRIMARY KEY ("ID_ARCHIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO" MODIFY ("NOMBRE" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO" MODIFY ("RUTA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO" MODIFY ("ESTADO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO" MODIFY ("FECHA_SUBIDA" NOT NULL ENABLE)
