--------------------------------------------------------
--  Ref Constraints for Table GRL_SUBCOMPONENTE
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_SUBCOMPONENTE" ADD CONSTRAINT "GRL_COMPONENTE_COMPO_FK" FOREIGN KEY ("ID_COMPONENTE")
	  REFERENCES "GENERALIDADES"."GRL_COMPONENTE" ("ID_COMPONENTE") ENABLE NOVALIDATE
  ALTER TABLE "GENERALIDADES"."GRL_SUBCOMPONENTE" ADD CONSTRAINT "GRL_COMPONENTE_PADRE_FK" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "GENERALIDADES"."GRL_COMPONENTE" ("ID_COMPONENTE") ENABLE NOVALIDATE
