--------------------------------------------------------
--  Constraints for Table GRL_PERSONA
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("ID_PERSONA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("IDENTIFICADOR" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("ID_TIPO_ID" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("NOMBRES" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("PRIMER_APELLIDO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("ID_SEXO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("ID_GENERO" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" MODIFY ("ID_NACIONALIDAD" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" ADD CONSTRAINT "FALLECIDO_CHECK" CHECK (FALLECIDO in ('S','N')) ENABLE
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" ADD CONSTRAINT "CON_DISCAPACIDAD_CHECK" CHECK (CON_DISCAPACIDAD in ('S', 'N')) ENABLE
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA" ADD CONSTRAINT "GRL_PERSONAS_PK" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE
