--------------------------------------------------------
--  Constraints for Table GRL_PERSONA_DIRECCION
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_PERSONA_DIRECCION" MODIFY ("ID_PERSONA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA_DIRECCION" MODIFY ("ID_DIRECCION" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA_DIRECCION" MODIFY ("ID_TIPO" NOT NULL ENABLE)
