--------------------------------------------------------
--  Constraints for Table GRL_REFERENCIA_SISTEMA
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" ADD CONSTRAINT "PK_REFERENCIA_SISTEMA" PRIMARY KEY ("ID_REFERENCIA", "ID_SISTEMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" MODIFY ("ID_REFERENCIA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" MODIFY ("ID_SISTEMA" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" MODIFY ("FECHA_REG" NOT NULL ENABLE)
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" MODIFY ("USER_REG" NOT NULL ENABLE)
