--------------------------------------------------------
--  Ref Constraints for Table GRL_ELEMENTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" ADD CONSTRAINT "GRL_ELEMENTO_FK" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "GENERALIDADES"."GRL_ELEMENTO" ("ID_ITEM") ENABLE NOVALIDATE
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO" ADD CONSTRAINT "GRL_ELEMENTO_COMPONENTE_FK" FOREIGN KEY ("ID_COMPONENTE")
	  REFERENCES "GENERALIDADES"."GRL_COMPONENTE" ("ID_COMPONENTE") ENABLE NOVALIDATE
