--------------------------------------------------------
--  DDL for Index IDX_PARAMETRO_VIGENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENERALIDADES"."IDX_PARAMETRO_VIGENTE" ON "GENERALIDADES"."GRL_PARAMETRO" (CASE "ID_ESTADO" WHEN 2256 THEN NULL ELSE UPPER("NOMBRE") END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"
