--------------------------------------------------------
--  DDL for Index IDX_REFITEM_VALIDACION
--------------------------------------------------------

  CREATE INDEX "GENERALIDADES"."IDX_REFITEM_VALIDACION" ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" ("ID_ITEM", "ID_REFERENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"
