
create public synonym CONST for GENERALIDADES.PKG_GRL_CONFIG;
grant execute on GENERALIDADES.PKG_GRL_CONFIG to CALIDAD;

---

create public synonym PKG_LOG for GENERALIDADES.PKG_LOG;
grant execute on GENERALIDADES.PKG_LOG to CALIDAD;

--

create public synonym REF_ITEM for GENERALIDADES.PKG_REFERENCIA_ITEM;
grant execute on GENERALIDADES.PKG_REFERENCIA_ITEM to CALIDAD;


--
CREATE PUBLIC SYNONYM TO_FLOAT_SYN FOR GENERALIDADES.TO_FLOAT_SYN;
grant execute on GENERALIDADES.TO_FLOAT_SYN to CALIDAD;
/

CREATE public SYNONYM UTILIDADES FOR GENERALIDADES.PKG_UTILIDADES;
grant execute on GENERALIDADES.PKG_UTILIDADES to CALIDAD;
/

CREATE public SYNONYM VALIDATOR FOR GENERALIDADES.PKG_VALIDATOR;
grant execute on GENERALIDADES.PKG_VALIDATOR to CALIDAD;
/

CREATE public SYNONYM REFERENCIA_ITEM FOR GENERALIDADES.GRL_REFERENCIA_ITEM;
grant SELECT on GENERALIDADES.GRL_REFERENCIA_ITEM to CALIDAD;


CREATE public SYNONYM REFERENCIA FOR GENERALIDADES.GRL_REFERENCIA;
grant SELECT on GENERALIDADES.GRL_REFERENCIA to CALIDAD;
/

CREATE public SYNONYM T_RULES FOR GENERALIDADES.T_RULES;
grant EXECUTE on GENERALIDADES.T_RULES to CALIDAD;

 

