--------------------------------------------------------
--  DDL for Package PKG_PERSONA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PACKAGE "GENERALIDADES"."PKG_PERSONA" AS   
    
    PROCEDURE GET_ALL (
        p_id IN NUMBER DEFAULT NULL,
        p_rut IN VARCHAR2 DEFAULT NULL,
        p_cursor OUT CLOB
    );

    PROCEDURE INSERT_GRL_PERSONA (
        P_IDENTIFICADOR     IN VARCHAR2,
        P_ID_TIPO_ID        IN NUMBER,    
        P_NOMBRES           IN VARCHAR2,
        P_PRIMER_APELLIDO   IN VARCHAR2,
        P_SEGUNDO_APELLIDO  IN VARCHAR2 DEFAULT NULL,
        P_FECHA_NAC         IN DATE DEFAULT NULL,
        P_NOMBRE_SOCIAL     IN VARCHAR2 DEFAULT NULL,
        P_ID_SEXO           IN NUMBER,
        P_ID_GENERO         IN NUMBER,
        P_OTRO_GENERO       IN VARCHAR2 DEFAULT NULL,
        P_CON_DISCAPACIDAD  IN VARCHAR2 DEFAULT 'N',
        P_DISCAPACIDAD      IN VARCHAR2 DEFAULT NULL,
        P_ID_NACIONALIDAD   IN NUMBER,
        P_FALLECIDO         IN VARCHAR2 DEFAULT 'N',
        P_ID_USUARIO_MOD    IN NUMBER DEFAULT NULL,
        P_FEC_ULT_MOD       IN DATE DEFAULT SYSDATE,
        O_ID_PERSONA        OUT NUMBER
    );

    PROCEDURE INSERT_GRL_PERSONA_DATO_PERSONAL (
        P_ID_PERSONA          IN NUMBER,
        P_CELULAR             IN VARCHAR2 DEFAULT NULL,
        P_FONO                IN VARCHAR2 DEFAULT NULL,
        P_EMAIL               IN VARCHAR2 DEFAULT NULL,
        P_FEC_ULT_ACT         IN DATE DEFAULT SYSDATE,
        P_ID_ESTADO_CIVIL     IN NUMBER DEFAULT NULL,
        P_ID_SITUAC_MILITAR   IN NUMBER DEFAULT NULL,
        P_ID_USUARIO_MOD      IN NUMBER DEFAULT NULL,
        P_FEC_ULT_MOD         IN DATE DEFAULT SYSDATE
    );

    PROCEDURE INSERT_GRL_DIRECCION (        
        P_CALLE                   IN VARCHAR2,
        P_NUMERO                  IN VARCHAR2,
        P_DEPTO                   IN VARCHAR2 DEFAULT NULL,
        P_ID_COMUNA               IN NUMBER DEFAULT NULL,
        P_ID_REGION               IN NUMBER DEFAULT NULL,
        P_ID_CLASE_DIRECCION      IN NUMBER DEFAULT NULL,
        P_LATITUD                 IN NUMBER DEFAULT NULL,
        P_LONGITUD                IN NUMBER DEFAULT NULL,
        P_COD_POSTAL              IN VARCHAR2 DEFAULT NULL,
        P_CIUDAD                  IN VARCHAR2 DEFAULT NULL,
        P_ID_PAIS                 IN NUMBER DEFAULT NULL,
        P_FEC_ULT_ACT             IN DATE DEFAULT NULL,
        P_ID_USUARIO_MOD          IN NUMBER DEFAULT NULL,
        O_ID_DIRECCION            OUT NUMBER,
        O_RESPUESTA               OUT VARCHAR2
    );

    PROCEDURE INSERT_GRL_PERSONA_DIRECCION (
        ID_PERSONA      IN NUMBER,    
        ID_DIRECCION    IN NUMBER,
        ID_TIPO         IN NUMBER,
        O_RESPUESTA     OUT VARCHAR2
    );   

    PROCEDURE GUARDAR_PERSONA (
        P_JSON IN CLOB,
        P_CURSOR        OUT SYS_REFCURSOR
    );

    FUNCTION MENSAJE_RETORNO (
        P_TIPO IN VARCHAR2,
        P_MENSAJE IN VARCHAR2
    ) RETURN SYS_REFCURSOR;

    FUNCTION SQLERRM_SIN_CODIGO (
        P_SQLERRM IN VARCHAR2
    ) RETURN VARCHAR2;

    FUNCTION GETNOMBRE_PERSONA (
        p_id IN      grl_persona.id_persona%type, 
        p_formato in NUMBER DEFAULT NULL        
    ) RETURN varchar2;


END PKG_PERSONA;

/

  GRANT EXECUTE ON "GENERALIDADES"."PKG_PERSONA" TO "SECRETARIAGRALDTIC";
  GRANT EXECUTE ON "GENERALIDADES"."PKG_PERSONA" TO "SIGESUSTIC";
