--------------------------------------------------------
--  DDL for Index GDP_DATOSPERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENERALIDADES"."GDP_DATOSPERSONA_PK" ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" ("ID_PERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX";
