--------------------------------------------------------
--  Ref Constraints for Table GRL_ELEMENTO_PADRE
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" ADD CONSTRAINT "GRL_ELEMENTO_ELTO_FK" FOREIGN KEY ("ID_ITEM")
	  REFERENCES "GENERALIDADES"."GRL_ELEMENTO" ("ID_ITEM") ENABLE NOVALIDATE;
  ALTER TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" ADD CONSTRAINT "GRL_ELEMENTO_PADRE_FK" FOREIGN KEY ("ID_PADRE")
	  REFERENCES "GENERALIDADES"."GRL_ELEMENTO" ("ID_ITEM") ENABLE NOVALIDATE;
