--------------------------------------------------------
--  DDL for Table GRL_DIRECCION
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_DIRECCION" 
   (	"ID_DIRECCION" NUMBER, 
	"CALLE" VARCHAR2(100 CHAR), 
	"NUMERO" VARCHAR2(10 CHAR), 
	"DEPTO" VARCHAR2(10 CHAR), 
	"ID_COMUNA" NUMBER, 
	"ID_REGION" NUMBER, 
	"ID_CLASE_DIRECCION" NUMBER, 
	"LATITUD" NUMBER, 
	"LONGITUD" NUMBER, 
	"COD_POSTAL" VARCHAR2(10 CHAR), 
	"CIUDAD" VARCHAR2(20 CHAR), 
	"ID_PAIS" NUMBER, 
	"FEC_ULT_ACT" DATE, 
	"ID_USUARIO_MOD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."ID_DIRECCION" IS 'ID único de la dirección, PK.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."CALLE" IS 'Nombre de la calle, avda, pasaje, etc..';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."NUMERO" IS 'Número de la casa, block, torre, etc.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."DEPTO" IS 'Número del departamento, opcional.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."ID_COMUNA" IS 'ID de la comuna de la dirección, solo para Chile.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."ID_REGION" IS 'ID de la región de la dirección, solo para Chile.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."ID_CLASE_DIRECCION" IS 'ID de la clase de dirección registrada: Nacional - Extranjera';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."LATITUD" IS 'Latitud de la dirección (GPS).';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."LONGITUD" IS 'Longitud de la dirección (GPS).';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."COD_POSTAL" IS 'Código postal de la dirección.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."CIUDAD" IS 'Nombre de la ciudad, solo para extranjeros.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."ID_PAIS" IS 'ID del pais de la dirección, obligatorio.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DIRECCION"."FEC_ULT_ACT" IS 'Fecha de la ultima actualización de la dirección.';
   COMMENT ON TABLE "GENERALIDADES"."GRL_DIRECCION"  IS 'Tabla que registra las direcciones de las personas (residencia, familiar, comercial, etc).';
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPGRL";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "AUDITOR";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPLOG";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGESUSTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSSGU";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIREPER";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSRP";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGETIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSTK";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "AUDITOR";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPLOG";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGESUSTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSSGU";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIREPER";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSRP";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGETIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSTK";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "AUDITOR";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPLOG";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSSGU";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSRP";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGETIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSTK";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "AUDITOR";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPLOG";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGESUSTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSSGU";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIREPER";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSRP";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "SIGETIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPSTK";
  GRANT DELETE ON "GENERALIDADES"."GRL_DIRECCION" TO "APPGRL";
