--------------------------------------------------------
--  Constraints for Table GRL_REFERENCIA_ROL
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" MODIFY ("ID_REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" MODIFY ("ID_ROL" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" MODIFY ("FECHA_REG" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" MODIFY ("USER_REG" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" ADD CONSTRAINT "PK_REFERENCIA_ROL" PRIMARY KEY ("ID_REFERENCIA", "ID_ROL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE;
