--------------------------------------------------------
--  DDL for Table GRL_ELEMENTO_PADRE
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE" 
   (	"ID_ITEM" NUMBER, 
	"ID_PADRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO_PADRE"."ID_ITEM" IS 'ID del elemento (hijo).';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ELEMENTO_PADRE"."ID_PADRE" IS 'ID del elemento padre.';
   COMMENT ON TABLE "GENERALIDADES"."GRL_ELEMENTO_PADRE"  IS 'Tabla que permite la relación que un item pueda tener más de un padre.';
