--------------------------------------------------------
--  Constraints for Table GRL_REFERENCIA
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA" MODIFY ("ID_REFERENCIA" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA" MODIFY ("FECHA_REG" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_REFERENCIA" ADD CONSTRAINT "GRL_REFERENCIA_PK" PRIMARY KEY ("ID_REFERENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE;
