--------------------------------------------------------
--  Constraints for Table GRL_ESTRUCTURA
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ESTRUCTURA" MODIFY ("ID_ESTRUCTURA" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_ESTRUCTURA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_ESTRUCTURA" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_ESTRUCTURA" ADD PRIMARY KEY ("ID_ESTRUCTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA"  ENABLE;
