--------------------------------------------------------
--  DDL for Table GRL_REFERENCIA_ITEM
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_REFERENCIA_ITEM" 
   (	"ID_ITEM" NUMBER, 
	"ID_REFERENCIA" NUMBER, 
	"NOMBRE" VARCHAR2(500 BYTE), 
	"VALOR_EXT" VARCHAR2(500 BYTE), 
	"ID_TIPO_DATO" VARCHAR2(10 BYTE), 
	"NIVEL" NUMBER, 
	"ID_PADRE" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"FECHA_REG" DATE DEFAULT sysdate, 
	"USER_REG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 70 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."ID_ITEM" IS 'ID de la item de referencia';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."ID_REFERENCIA" IS 'ID de la referencia a la que pertenece.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."NOMBRE" IS 'Nombre de la referencia';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."VALOR_EXT" IS 'Valor de la referencia usado por otros sistemas externos, o valor necesario.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."ID_TIPO_DATO" IS 'Indica el tipo de datos: CHAR, INT, NUMBER, DATE';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."NIVEL" IS 'Default cero, indica el nivel del elemento en la jerarquia. (0..N)';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."ID_PADRE" IS 'ID del elemento superior, solo en caso de ser jerarquica.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."ID_ESTADO" IS 'Estado del elemento: 0 -> Inactivo; 1 -> Activo';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."FECHA_REG" IS 'Fecha en que se hace el registro de la referencia.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ITEM"."USER_REG" IS 'ID del usuario que crea la referencia.';
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SECRETARIAGRALDTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SECRETARIAGRALDTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "GESTPERSDTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "GESTPERSDTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIEVAUTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIEVAUTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "DACIDTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "DACIDTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "CALIDAD";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "AUDITOR";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPLOG";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGESUSTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSSGU";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIREPER";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSRP";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGETIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSTK";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "AUDITOR";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPLOG";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGESUSTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSSGU";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIREPER";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSRP";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGETIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSTK";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "AUDITOR";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPLOG";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSSGU";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSRP";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGETIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSTK";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "AUDITOR";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPLOG";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGESUSTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSSGU";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIREPER";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSRP";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGETIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPSTK";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPGRL";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "APPGRL";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "AUDITOR";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGESUSTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIGETIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESAPPS";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIACPATESTAPPS";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "SIACPATESTTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESAPPS";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESAPPS";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESAPPS";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESAPPS";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" TO "NOTIFICACIONESTIC";
