--------------------------------------------------------
--  Constraints for Table GRL_PARAMETRO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_TIPO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_MODULO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "PARAMETRO_PK" PRIMARY KEY ("ID_PARAMETRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA"  ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_TIPO_DATO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_SISTEMA_POS" CHECK (id_sistema > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_MODULO_POS" CHECK (id_modulo > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_TIPO_POS" CHECK (id_tipo > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_ESTADO_POS" CHECK (id_estado > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_USUARIO_POS" CHECK (id_usuario > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" ADD CONSTRAINT "CHK_ID_TIPO_DATO_POS" CHECK (id_tipo_dato > 0) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("FECHA_REG" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("USER_REG" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_APLICACION" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("VALOR" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_PARAMETRO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PARAMETRO" MODIFY ("ID_SISTEMA" NOT NULL ENABLE);
