--------------------------------------------------------
--  DDL for Table GRL_REFERENCIA_SISTEMA
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" 
   (	"ID_REFERENCIA" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"FECHA_REG" DATE DEFAULT SYSDATE, 
	"USER_REG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_SISTEMA"."ID_REFERENCIA" IS 'ID de la referencia.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_SISTEMA"."ID_SISTEMA" IS 'ID del sistema que es propietario de la referencia';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_SISTEMA"."FECHA_REG" IS 'Fecha de asignación, valor default SYSDATE.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_SISTEMA"."USER_REG" IS 'Usuario de Registro';
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPGRL";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPGRL";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPLOG";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPLOG";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPLOG";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPLOG";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSRP";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSRP";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSRP";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSRP";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSSGU";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSSGU";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSSGU";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSSGU";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSTK";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSTK";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSTK";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "APPSTK";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "AUDITOR";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "AUDITOR";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "AUDITOR";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "AUDITOR";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGESUSTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGESUSTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGESUSTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGETIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGETIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGETIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIGETIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIREPER";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIREPER";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_SISTEMA" TO "SIREPER";
