--------------------------------------------------------
--  DDL for Table GRL_PARAMETRO
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_PARAMETRO" 
   (	"ID_PARAMETRO" NUMBER, 
	"ID_SISTEMA" NUMBER, 
	"ID_MODULO" NUMBER, 
	"ID_APLICACION" NUMBER, 
	"NOMBRE" VARCHAR2(30 CHAR), 
	"DESCRIPCION" VARCHAR2(2000 CHAR), 
	"VALOR" VARCHAR2(1000 CHAR), 
	"ID_TIPO" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"ID_USUARIO" NUMBER, 
	"ID_TIPO_DATO" NUMBER, 
	"FECHA_REG" DATE DEFAULT SYSDATE, 
	"USER_REG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_PARAMETRO" IS 'Identificador del parametro.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_SISTEMA" IS 'ID del sistema donde aplica el parametro';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_MODULO" IS 'ID del modulo donde aplica, opcional.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_APLICACION" IS 'ID de la apliacción que utiliza el parametro.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."NOMBRE" IS 'Nombre del parametro.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."DESCRIPCION" IS 'Descripcón del parametro, para que se usa, valores posible, restricciones, etc.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."VALOR" IS 'Valor del parametro.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_TIPO" IS 'Tipo de parametro: SISTEMA, USUARIO, PROCESO';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_ESTADO" IS 'Estado del elemento: Inactivo, Activo';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_USUARIO" IS 'El ID de usuario que actualizó por ultima vez el paramtero.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."ID_TIPO_DATO" IS 'ID del tipo de datos para el parametro:  NUMBER, INT, CHAR, DATE';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."FECHA_REG" IS 'Fecha registro del parametro';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PARAMETRO"."USER_REG" IS 'Usuario que registra el parametro';
  GRANT DELETE ON "GENERALIDADES"."GRL_PARAMETRO" TO "APPGRL";
  GRANT INSERT ON "GENERALIDADES"."GRL_PARAMETRO" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_PARAMETRO" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PARAMETRO" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_PARAMETRO" TO "SIGESUSTIC";
