--------------------------------------------------------
--  Constraints for Table GRL_COMPONENTE
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_COMPONENTE" MODIFY ("ID_ESTRUCTURA" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_COMPONENTE" MODIFY ("ID_COMPONENTE" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_COMPONENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_COMPONENTE" ADD CONSTRAINT "GRL_COMPONENTE_PK" PRIMARY KEY ("ID_COMPONENTE")
  USING INDEX "GENERALIDADES"."GRL_COMPONENTE_PK"  ENABLE;
