--------------------------------------------------------
--  Ref Constraints for Table GRL_ATRIBUTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" ADD CONSTRAINT "GLR_ATRIBUTO_COMPONENTE_FK" FOREIGN KEY ("ID_COMPONENTE")
	  REFERENCES "GENERALIDADES"."GRL_COMPONENTE" ("ID_COMPONENTE") ENABLE NOVALIDATE;
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" ADD CONSTRAINT "GLR_ATRIBUTO_TIPO_FK" FOREIGN KEY ("ID_TIPO_DATO")
	  REFERENCES "GENERALIDADES"."GRL_REFERENCIA_ITEM" ("ID_ITEM") ENABLE NOVALIDATE;
  ALTER TABLE "GENERALIDADES"."GRL_ATRIBUTO" ADD CONSTRAINT "GLR_ATRIBUTOS_ESTADO_FK" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "GENERALIDADES"."GRL_REFERENCIA_ITEM" ("ID_ITEM") ENABLE NOVALIDATE;
