--------------------------------------------------------
--  DDL for Table GRL_ESTRUCTURA
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ESTRUCTURA" 
   (	"ID_ESTRUCTURA" NUMBER, 
	"NOMBRE" VARCHAR2(60 CHAR), 
	"DESCRIPCION" VARCHAR2(2000 CHAR), 
	"ID_ESTADO" NUMBER, 
	"PUNTO_INICIO" NUMBER, 
	"ID_TIPO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ESTRUCTURA"."ID_ESTRUCTURA" IS 'ID de la estructura.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ESTRUCTURA"."NOMBRE" IS 'Nombre de la estructura';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ESTRUCTURA"."DESCRIPCION" IS 'Describe para que es la estructua.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ESTRUCTURA"."ID_ESTADO" IS 'Indica el estado de la estructura: VIGENTE - NO VIGENTE';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ESTRUCTURA"."ID_TIPO" IS 'ID del tipo de estructira: jerarquica - proceso  ';
