--------------------------------------------------------
--  DDL for Table GRL_PERSONA_DATO_PERSONAL
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" 
   (	"ID_PERSONA" NUMBER, 
	"CELULAR" VARCHAR2(20 CHAR), 
	"FONO" VARCHAR2(20 CHAR), 
	"EMAIL" VARCHAR2(100 CHAR), 
	"FEC_ULT_ACT" DATE DEFAULT SYSDATE, 
	"ID_ESTADO_CIVIL" NUMBER, 
	"ID_SITUAC_MILITAR" NUMBER, 
	"ID_USUARIO_MOD" NUMBER, 
	"FEC_ULT_MOD" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."ID_PERSONA" IS 'ID único de la persona, PK.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."CELULAR" IS 'Número de celular de la persona, opcional.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."FONO" IS 'Número de telefono de la persona (particular), opcional.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."EMAIL" IS 'Email personal.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."FEC_ULT_ACT" IS 'Fecha de la ultima actualización de alguno de los datos de la tabla.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."ID_ESTADO_CIVIL" IS 'ID del estado civil de la persona.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"."ID_SITUAC_MILITAR" IS 'ID de la situación militar de la persona, opcional.';
   COMMENT ON TABLE "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL"  IS 'Tabla que registra los datos más variables de la presona y datos de referencia general.';
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "AUDITOR";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPLOG";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGESUSTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSSGU";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIREPER";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSRP";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGETIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSTK";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "AUDITOR";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPLOG";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGESUSTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSSGU";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIREPER";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSRP";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGETIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSTK";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "AUDITOR";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPLOG";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSSGU";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSRP";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGETIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSTK";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "AUDITOR";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPLOG";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGESUSTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSSGU";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIREPER";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSRP";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "SIGETIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPSTK";
  GRANT DELETE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPGRL";
  GRANT INSERT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" TO "APPGRL";
