--------------------------------------------------------
--  DDL for Table GRL_REFERENCIA
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_REFERENCIA" 
   (	"ID_REFERENCIA" NUMBER, 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"DESCRIPCION" VARCHAR2(500 BYTE), 
	"ID_TIPO" NUMBER, 
	"ID_CLASE" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"FECHA_REG" DATE, 
	"USER_REG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 80 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."ID_REFERENCIA" IS 'ID de la referencia';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."NOMBRE" IS 'Nombre de la referencia.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."DESCRIPCION" IS 'Descripcón de la referencia, que contiene y para que se usa.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."ID_TIPO" IS 'Tipo de a referencia: 100: SISTEMA; 110: USUARIO';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."ID_CLASE" IS 'Indica la clase de la referencia: 120: Líneal; 130: Jerarquica';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."ID_ESTADO" IS 'Estado de la referencia: 0: Inactivo; 1: Activo';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."FECHA_REG" IS 'Fecha de creación, valor default SYSDATE.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA"."USER_REG" IS 'ID del usuario que crea la referencia.';
   COMMENT ON TABLE "GENERALIDADES"."GRL_REFERENCIA"  IS 'Tabla que define las referencias del sistema, tanto las referencias de sistema o técnicas como las de usuario.';
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA" TO "SIGESUSTIC";
  GRANT REFERENCES ON "GENERALIDADES"."GRL_REFERENCIA" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA" TO "CALIDAD";
