--------------------------------------------------------
--  DDL for Table GRL_ATRIBUTO
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_ATRIBUTO" 
   (	"ID_ATRIBUTO" NUMBER, 
	"ID_COMPONENTE" NUMBER, 
	"NOMBRE" VARCHAR2(30 CHAR), 
	"ID_TIPO_DATO" NUMBER, 
	"LARGO" NUMBER, 
	"POSICION" NUMBER, 
	"ID_ESTADO" NUMBER, 
	"OBJETO" VARCHAR2(100 CHAR), 
	"COLUMNA_ID" VARCHAR2(60 CHAR), 
	"COLUMNA_DATA" VARCHAR2(60 CHAR), 
	"OBLIGATORIO" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"VALOR_DEFAULT" VARCHAR2(2000 CHAR), 
	"MASCARA" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."NOMBRE" IS 'Nombre del atributo, visible al usuario';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."ID_TIPO_DATO" IS 'ID del tipo de datos del atributo';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."LARGO" IS 'En caso de CHAR o TEXTO el largo de caracteres';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."POSICION" IS 'Posicion u orden del campo, 1..N';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."ID_ESTADO" IS 'ID del estado del atributo: VIGENTE - NO VIGENTE';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."OBJETO" IS 'Nombre de la tabla o vista de donde se obtiene un dato.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."COLUMNA_ID" IS 'Nombre de la columna del objeto para la busqueda del dato.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."COLUMNA_DATA" IS 'Nombre de la columna del objeto que tiene el dato que debe recuperarse.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."OBLIGATORIO" IS 'Indica si el campo es obligatorio o no S/N.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_ATRIBUTO"."VALOR_DEFAULT" IS 'Valor default para el atributo.';
