--------------------------------------------------------
--  DDL for Table GRL_REFERENCIA_ROL
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_REFERENCIA_ROL" 
   (	"ID_REFERENCIA" NUMBER, 
	"ID_ROL" NUMBER, 
	"FECHA_REG" DATE DEFAULT SYSDATE, 
	"USER_REG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ROL"."ID_REFERENCIA" IS 'ID de la referencia.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ROL"."ID_ROL" IS 'ID del rol que tiene acceso a la referencia.';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_REFERENCIA_ROL"."FECHA_REG" IS 'Fecha de habilitación del rol, SYSDATE';
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "AUDITOR";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPLOG";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGESUSTIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSSGU";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIREPER";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSRP";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGETIC";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSTK";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "AUDITOR";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPLOG";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGESUSTIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSSGU";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIREPER";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSRP";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGETIC";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSTK";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "AUDITOR";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPLOG";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGESUSTIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSSGU";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIREPER";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSRP";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGETIC";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSTK";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "AUDITOR";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPLOG";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGESUSTIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSSGU";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIREPER";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSRP";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "SIGETIC";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPSTK";
  GRANT DELETE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPGRL";
  GRANT INSERT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPGRL";
  GRANT SELECT ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPGRL";
  GRANT UPDATE ON "GENERALIDADES"."GRL_REFERENCIA_ROL" TO "APPGRL";
