--------------------------------------------------------
--  Constraints for Table GRL_DATO_ELEMENTO
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" MODIFY ("ID_ITEM" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" MODIFY ("ID_ATRIBUTO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" ADD CONSTRAINT "GRL_DATO_ELEMENTO_PK" PRIMARY KEY ("ID_ITEM", "ID_ATRIBUTO")
  USING INDEX "GENERALIDADES"."GRL_DATO_ELEMENTO_PK"  ENABLE;
