--------------------------------------------------------
--  Constraints for Table GRL_ARCHIVO_VERSION
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" ADD PRIMARY KEY ("ID_VERSION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA"  ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" ADD CHECK (metadata IS JSON) ENABLE;
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" MODIFY ("ID_ARCHIVO" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" MODIFY ("FECHA_MODIFICACION" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_ARCHIVO_VERSION" MODIFY ("ESTADO" NOT NULL ENABLE);
