--------------------------------------------------------
--  Constraints for Table GRL_PERSONA_DATO_PERSONAL
--------------------------------------------------------

  ALTER TABLE "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" MODIFY ("ID_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "GENERALIDADES"."GRL_PERSONA_DATO_PERSONAL" ADD CONSTRAINT "GDP_DATOSPERSONA_PK" PRIMARY KEY ("ID_PERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX"  ENABLE;
