--------------------------------------------------------
--  DDL for Table GRL_DATO_ELEMENTO
--------------------------------------------------------

  CREATE TABLE "GENERALIDADES"."GRL_DATO_ELEMENTO" 
   (	"ID_ITEM" NUMBER, 
	"ID_ATRIBUTO" NUMBER, 
	"VALOR" VARCHAR2(2000 CHAR), 
	"ULT_FEC_ACT" DATE, 
	"ID_USUARIO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_DATA";

   COMMENT ON COLUMN "GENERALIDADES"."GRL_DATO_ELEMENTO"."VALOR" IS 'Valor del campo';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DATO_ELEMENTO"."ULT_FEC_ACT" IS 'Utima fecha de actualizacion';
   COMMENT ON COLUMN "GENERALIDADES"."GRL_DATO_ELEMENTO"."ID_USUARIO" IS 'ID del usuario que hizo ultima modificacion';
