--------------------------------------------------------
--  DDL for Index IDX_REFERENCIA_ITEM_VIGENTE
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENERALIDADES"."IDX_REFERENCIA_ITEM_VIGENTE" ON "GENERALIDADES"."GRL_REFERENCIA_ITEM" (CASE  WHEN "ID_ESTADO"<>127 THEN "ID_REFERENCIA" END , CASE  WHEN "ID_ESTADO"<>127 THEN "NIVEL" END , CASE  WHEN "ID_ESTADO"<>127 THEN "ID_PADRE" END , CASE  WHEN "ID_ESTADO"<>127 THEN UPPER("NOMBRE") END ) 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX";
