--------------------------------------------------------
--  DDL for Index PK_REFERENCIA_ROL
--------------------------------------------------------

  CREATE UNIQUE INDEX "GENERALIDADES"."PK_REFERENCIA_ROL" ON "GENERALIDADES"."GRL_REFERENCIA_ROL" ("ID_REFERENCIA", "ID_ROL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "GENERALIDADES_INDEX";
